### ISSUE TITLE
Dataprocessors must be static

### ISSUE THREAD

**Issue by bwaidelich** [bwaidelich/Wwwision.ImportService#2]
## Steps to reproduce

Configure a preset with some `dataProcessor`:

```yaml
Wwwision:
  ImportService:
    presets:
      'somePreset':
        options:
          dataProcessor: 'Some\Package\SomeProcessor::foo'
```

and run the import command

### Expected result

an instance of the `SomeProcessor` class is instantiated and the `foo()` method is called

### Actual result

Exception:
```
Error while loading preset "somePreset": Option "dataProcessor" must be a callable in the format: "Some\ClassName::someMethodName" but it is: "Some\Package\SomeProcessor::foo" and that is not callable
```
